src/Entity/Tweet.php
<?php

namespace App\Entity;

use App\Repository\TweetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TweetRepository::class)
 */
class Tweet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Cette news est trop courte !", maxMessage="Cette news est trop longue !")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=user::class, inversedBy="tweets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\ManyToOne(targetEntity=Tweet::class, inversedBy="children")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Tweet::class, mappedBy="parent")
     */
    private $children;

    /**
     * List of Users who like this Tweet
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="likedTweets")
     * @ORM\JoinTable("user_like_tweet")
     */
    private $likers;


    public function __construct()
    {
        $this->children = new ArrayCollection();
        $this->likers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUserId(): ?user
    {
        return $this->user_id;
    }

    public function setUserId(?user $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChild(self $child): self
    {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(self $child): self
    {
        if ($this->children->removeElement($child)) {
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getLikers(): Collection
    {
        return $this->likers;
    }

    public function addLiker(User $liker): self
    {
        if (!$this->likers->contains($liker)) {
            $this->likers[] = $liker;
            $liker->addLikedTweet($this);
        }

        return $this;
    }

    public function removeLiker(User $liker): self
    {
        if ($this->likers->removeElement($liker)) {
            $liker->removeLikedTweet($this);
        }

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\OneToMany(targetEntity=Tweet::class, mappedBy="user_id", orphanRemoval=true)
     */
    private $tweets;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $years;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * List of Tweets liked by this User
     * @ORM\ManyToMany(targetEntity=Tweet::class, inversedBy="likers")
     * @ORM\JoinTable("user_like_tweet")
     */
    private $likedTweets;

    public function __construct()
    {
        $this->tweets = new ArrayCollection();
        $this->likedTweets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return Collection|Tweet[]
     */
    public function getTweets(): Collection
    {
        return $this->tweets;
    }

    public function addTweet(Tweet $tweet): self
    {
        if (!$this->tweets->contains($tweet)) {
            $this->tweets[] = $tweet;
            $tweet->setRelation($this);
        }

        return $this;
    }

    public function removeTweet(Tweet $tweet): self
    {
        if ($this->tweets->removeElement($tweet)) {
            // set the owning side to null (unless already changed)
            if ($tweet->getRelation() === $this) {
                $tweet->setRelation(null);
            }
        }

        return $this;
    }

    public function getYears(): ?string
    {
        return $this->years;
    }

    public function setYears(string $years): self
    {
        $this->years = $years;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection|Tweet[]
     */
    public function getLikedTweets(): Collection
    {
        return $this->likedTweets;
    }

    public function likeTweet(Tweet $likedTweet): self
    {
        if (!$this->likedTweets->contains($likedTweet)) {
            $this->likedTweets[] = $likedTweet;
        }

        return $this;
    }

    public function unlikeTweet(Tweet $likedTweet): self
    {
        $this->likedTweets->removeElement($likedTweet);

        return $this;
    }

    public function doesLike(Tweet $tweet): bool {
        return $this->likedTweets->contains($tweet);
    }

}

templates/fragment/_all_friends.html.twig
{% for user in all_users %}
    <div class="w-full mx-auto bg-gray-800 p-10 rounded-md text-white grid grid-cols-12 col-span-1">
        <div class="col-span-4">
            <img class="h-20 w-20 rounded-full bg-gray-500" src="img/{{ user.picture }}" alt="">
        </div>
        <div class="col-span-8 h-full flex flex-col justify-between">
            <div class="flex gap-x-4">
                <p>{{ user.firstName }}</p>
                <p>{{ user.lastName }}</p>
            </div>
            <a class="bg-gray-300 text-white py-2 px-6 rounded-md" href="{{ path('app_profileUserPage', {id: user.id}) }}">Profile</a>
        </div>
    </div>
{% endfor %}

templates/fragment/_comment_tweet.htnl.twig
{% for comment in comments %}
    <div class="grid grid-cols-12 mb-10 p-10 rounded-xl bg-gray-200 shadow-xl">
        <div class="col-span-3 flex justify-center items-start">
            <img class="h-20 w-20 rounded-full bg-gray-800" src="{{ comment.userId.picture }}" alt="">
        </div>

        <div class="col-span-9">
            <div class="flex gap-x-3 mb-4">
                <a href="{{ path('app_profileUserPage', {id: comment.userId.id}) }}" class="flex gap-x-2">
                    <p>{{ comment.userId.firstName }}</p>
                    <p>{{ comment.userId.lastName }}</p>
                </a>
            </div>

            <p>{{ comment.message }}</p>
        </div>
    </div>

{% endfor %}

templates/fragment/_footer.html.twig
<footer>
    <div class="h-56 bg-gray-800 w-full flex justify-center items-center">
        <p class="text-white capitalize text-3xl">test footer</p>
    </div>
</footer>

templates/fragment/_header.html.twig
<header class="fixed top-0 z-50 w-full bg-gradient-to-r from-gray-900 via-gray-500 to-blue-50 flex justify-between">
    <ul class="flex shadow-2xl">
        <li class="text-white border-r border-white transition-all duration-200s hover:bg-blue-200 hover:text-gray-700">
            <a class="w-32 flex justify-center py-4" href="{{ path('app_feedPage') }}">Accueil</a>
        </li>

        <li class="text-white border-r border-white transition-all duration-200s hover:bg-blue-200 hover:text-gray-700">
            <a class="w-32 flex justify-center py-4" href="{{ path('app_friendsPage') }}">Amis</a>
        </li>

        <li class="text-white border-r border-white transition-all duration-200s hover:bg-blue-200 hover:text-gray-700">
            <a class="w-32 flex justify-center py-4" href="{{ path('app_profilePage') }}">Profile</a>
        </li>
    </ul>

    <div class="mr-6">
        {{ include('fragment/_logout.html.twig') }}
    </div>
</header>

templates/fragment/_header_profile.html.twig
<div class="relative bg-gray-800">
    <div class="w-full h-96 bg-gradient-to-br from-blue-400 via-green-300 to-pink-400"></div>
    <img class="absolute -bottom-28 left-44 h-60 w-60 rounded-full bg-gray-800 border-4 border-gray-800"
         src="img/{{ picture }}" alt="">
</div>

<div class="w-6/12 mx-auto flex gap-x-3 text-white text-3xl pt-10">
    <p>{{ user }}</p>
    <p>{{ last_name }}</p>
    <p>{{ years }}</p>
</div>

<div class="flex py-20 justify-center gap-x-10  w-10/12 mx-auto">
    <div class="w-8/12">
        {% include 'fragment/_news_profil.html.twig' %}
    </div>

    <div class="w-4/12 h-56 sticky top-24">
        {% include 'fragment/_news_form.html.twig' %}
    </div>
</div>

templates/fragment/_header_profile_user.html.twig
<div class="relative bg-gray-800">
    <div class="w-full h-96 bg-gradient-to-br from-blue-400 via-green-300 to-pink-400"></div>
    <img class="absolute -bottom-28 left-44 h-60 w-60 rounded-full bg-gray-800 border-4 border-gray-800"
         src="{{ asset('img/' ~ picture) }}" alt="">
</div>

<div class="w-6/12 mx-auto flex gap-x-3 text-white text-3xl pt-10">
    <p>{{ first_name }}</p>
    <p>{{ last_name }}</p>
    <p>{{ years }}</p>
</div>

<div class="flex py-20 justify-center gap-x-10 relative">
    <div class="w-6/12">
        {% include 'fragment/_news_profil.html.twig' %}
    </div>
</div>

templates/fragment/_logout.html.twig
<div class="z-50 flex items-center">
    <p class="m-4">Bonjour {{ user }}</p>
    <a class="bg-gray-800 text-white py-2 px-6 rounded-md" href="{{ path('app_logout') }}">Logout</a>
</div>

templates/fragment/_main_login.html.twig
<form class="flex flex-col" action="" method="posts">

    <label class="text-center my-4 text-white" for="mail">E.mail</label>
    <input class="w-80 bg-gray-300 rounded-md p-2" id="mail" name="mail" type="text">

    <label class="text-center my-4 text-white" for="password">Password</label>
    <input class="w-80 bg-gray-300 rounded-md p-2" id="password" name="password" type="text">

    <div class="flex justify-between items-center">
        <a class="text-center mt-10 w-28 p-2 bg-gray-800 text-white rounded-md hover:bg-white hover:text-gray-700 transition-all duration-300 cursor-pointer"
           href="{{ path('app_registerPage') }}">Inscription</a>
        <input class="mt-10 w-28 p-2 bg-gray-800 text-white rounded-md hover:bg-white hover:text-gray-700 transition-all duration-300 cursor-pointer"
               type="submit">
    </div>

</form>

templates/fragment/_main_register.html.twig
{{ form_start(formRegister) }}

<div class="flex flex-col mb-2">
    <div class="text-white">
        {{ form_label(formRegister.email, 'E.mail') }}
    </div>
    {{ form_errors(formRegister.email) }}
    {{ form_widget(formRegister.email, {'attr': {'class': 'rounded-md py-2 px-4'}}) }}
</div>

<div class="flex flex-col mb-2">
    <div class="text-white">
        {{ form_label(formRegister.password, 'Mot de passe') }}
    </div>
    {{ form_errors(formRegister.password) }}
    {{ form_widget(formRegister.password, {'attr': {'class': 'rounded-md py-2 px-4'}}) }}
</div>

<div class="flex gap-x-4">
    <div class="flex flex-col mb-2">
        <div class="text-white">
            {{ form_label(formRegister.first_name, 'Prenom') }}
        </div>
        {{ form_errors(formRegister.first_name) }}
        {{ form_widget(formRegister.first_name, {'attr': {'class': 'rounded-md py-2 px-4'}}) }}
    </div>

    <div class="flex flex-col mb-2">
        <div class="text-white">
            {{ form_label(formRegister.last_name, 'Nom') }}
        </div>
        {{ form_errors(formRegister.last_name) }}
        {{ form_widget(formRegister.last_name, {'attr': {'class': 'rounded-md py-2 px-4'}}) }}
    </div>
</div>

<div class="flex flex-col mb-10">
    <div class="flex flex-col mb-2">
        <div class="text-white">
            {{ form_label(formRegister.years, 'Annee de naissance') }}
        </div>
        {{ form_errors(formRegister.years) }}
        {{ form_widget(formRegister.years, {'attr': {'class': 'rounded-md py-2 px-4'}}) }}
    </div>

    <div class="flex flex-col mb-2 text-white">
        {{ form_label(formRegister.picture, 'Photo de profil') }}
        {{ form_errors(formRegister.picture) }}
        {{ form_widget(formRegister.picture) }}
    </div>
</div>

<button class="rounded-md text-white py-2 px-4 bg-gray-800 hover:bg-white hover:text-gray-700" type="submit">
    Enregistrer
</button>

{{ form_end(formRegister) }}

templates/fragment/_news_form.html.twig
<div class="flex-1 h-auto bg-gradient-to-b from-mango-500 via-green-300 to-indigo-300 rounded-xl p-3">
    <div class="flex flex-col">
        {{ form_start(formNews) }}

        {{ form_label(formNews.message, ' ') }}
        {{ form_errors(formNews.message) }}
        {{ form_widget(formNews.message, {'attr': {'placeholder': 'Rentrer une News', 'class': 'h-44 rounded-xl py-2 px-4 w-full'}}) }}

        <button class="rounded-md text-white py-2 px-4 bg-gray-800 hover:bg-white hover:text-gray-700" type="submit">Publier</button>

        {{ form_end(formNews) }}
    </div>
</div>

templates/fragment/_news_profil.html.twig
<div class="w-full h-full all_tweet">
  {% for tweet in tweet %}
    {% include 'fragment/_tweet.html.twig' %}
  {% endfor %}
</div>

templates/fragment/_tweet.html.twig
<div class="grid grid-cols-12 mb-10 p-10 rounded-xl bg-gray-200 shadow-xl">
    <div class="col-span-3 flex justify-center items-start">
        <img class="h-20 w-20 rounded-full bg-gray-500" src="img/{{ tweet.userId.picture }}" alt="">
    </div>

    <div class="col-span-9">
        <div class="flex gap-x-3 mb-4">
            <a href="{{ path('app_profileUserPage', {id: tweet.userId.id}) }}" class="flex gap-x-2">
                <p>{{ tweet.userId.firstName }}</p>
                <p>{{ tweet.userId.lastName }}</p>
            </a>
            <a href="{{ path('app_tweetPage', {id: tweet.id}) }}">
                <p>{{ tweet.createdAt | format_datetime("long", locale="fr") }}</p>
            </a>
        </div>

        <p>{{ tweet.message }}</p>

        <div class="mt-6 flex gap-x-2 card-footer">
            <a href="" class="flex items-center justify-center gap-x-2">
                <img src="{{ asset('img/chat-alt.svg') }}" alt="">
                <p>{{ tweet.parent | length }}</p>
            </a>
            <p>
                |
            </p>

            {% if app.user and app.user.doesLike(tweet) %}
                <a href="{{ path('app_tweet_like', { id: tweet.id }) }}"
                   class="flex items-center justify-center gap-x-2 link-like link-liked">
                    <img class="h-6" src="{{ asset('img/star-fill.svg') }}" alt="">
                </a>
            {% else %}
                <a href="{{ path('app_tweet_like', { id: tweet.id }) }}"
                   class="flex items-center justify-center gap-x-2 link-like">
                    <img class="h-6" src="{{ asset('img/star-empty.svg') }}" alt="">
                </a>
            {% endif %}
            <span>{{ tweet.likers | length }}</span>

        </div>
    </div>
</div>